modLoader = "javafml" #mandatory
loaderVersion = "[37.0,)" #mandatory
issueTrackerURL = "https://github.com/Alex-the-666/ice-and-fire/issues" #optional
license = "GNU LESSER GENERAL PUBLIC LICENSE"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons" #optional
authors = "Alexthe666, TheBv" #optional
description = '''Dragons and other mythological creatures in minecraft.'''

[[dependencies.iceandfire]] #optional
# the modid of the dependency
modId = "citadel" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[1.12.0,2.1.1]" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"

[[dependencies.iceandfire]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.iceandfire]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"